### PR TITLE
Change the new sintax for pg:backups

### PR DESCRIPTION
**Pull request by eduardofiorezi**
Related to #72 

More infos: https://devcenter.heroku.com/articles/heroku-postgres-backups

### CODE REVIEW

**Comment by marcioj** [comment]
@eduardofiorezi thanks. Would be nice to send a new release, but I believe I don't have permission to do it

**Comment by rodrigopinto** [comment]
@maurogeorge @eduardofiorezi Can I release the gem with this update?

**Comment by eduardofiorezi** [comment]
Yes, today the pah is broken.

**Comment by marcioj** [comment]
@rodrigopinto can you release the 0.0.6 for me please? I'd like to update `pah`. Helabs/pah#474 fixed the problem when generating a new app, but running `rake integrate` will display an error for the user, since it's using an outdated `jumpup-heroku` version.

**Comment by rodrigopinto** [comment]
@marcioj sorry I can collaborate on jumpup-heroku to make a `git push` bumping version. @maurogeorge @eduardofiorezi can you add this repo to my permissions please.

**Pull request merged**
